# Generated by Django 5.2 on 2025-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('talla', models.IntegerField()),
                ('color', models.CharField(default='sin color', max_length=30)),
                ('fecha_creacion', models.DateTimeField(null=True)),
            ],
        ),
    ]
