# Generated by Django 5.2 on 2025-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='talla',
            field=models.IntegerField(max_length=5),
        ),
    ]
