# Generated by Django 5.2 on 2025-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_zapato_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='color',
            field=models.CharField(default='sin color', max_length=30),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='talla',
            field=models.FloatField(),
        ),
    ]
