# Generated by Django 5.2 on 2025-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_zapato_color_alter_zapato_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='talla',
            field=models.IntegerField(),
        ),
    ]
